# Experiments with DL library in python
This notebook contains some experiments of library usage in python

# Tensorflow
[TensorFlow](https://www.tensorflow.org/) is an end-to-end open source platform for machine learning. It has a comprehensive, flexible ecosystem of tools, libraries and community resources that lets researchers push the state-of-the-art in ML and developers easily build and deploy ML powered applications.


## Imports and renaming

In [8]:
import tensorflow as tf
K = tf.keras
L = K.layers
seq = K.Sequential
tensor = tf.constant

## Tensors handling

In [30]:
## Creation
a = tensor([[1, 2]])
b = tensor([[4, 3]])
## Basic linear operation
print(a + b) ## 1 + 4, 3 + 2 => [5, 5]
print(a * b) ## 1 * 4, 2 * 3 => [4, 6]
print(a - b) ## 1 - 4, 2 - 3 => [-3, -1]
print(b * 2) ## 4 * 2, 3 * 2 => [8, 6]
print(b ** 2) ## 4 ^ 2, 3 ^ 2 => [16, 9]
c = tensor([[2], [3]])
print(a @ c) ## matrix multiplication, so: 1 * 2 + 3 * 2 = 8

tf.Tensor([[5 5]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[-3 -1]], shape=(1, 2), dtype=int32)
tf.Tensor([[8 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[16  9]], shape=(1, 2), dtype=int32)
tf.Tensor([[8]], shape=(1, 1), dtype=int32)


## Gradients

### Gradients evaluation in multiple model not linked between each other

In [49]:
model_a = seq(L.Dense(8))
model_b = seq(L.Dense(10))
with tf.GradientTape() as g:
    res = model_a(tensor([[1, 2]]))
    out = model_b(res)
    gradients = g.gradient(out, [model_a.weights, model_b.weights])
    print(gradients)

[[<tf.Tensor: shape=(2, 8), dtype=float32, numpy=
array([[-0.29641518, -0.43776062,  1.0762619 ,  0.15499532, -0.97992945,
         0.71167135,  1.2409165 , -0.58520615],
       [-0.59283036, -0.87552124,  2.1525238 ,  0.30999064, -1.9598589 ,
         1.4233427 ,  2.481833  , -1.1704123 ]], dtype=float32)>, <tf.Tensor: shape=(8,), dtype=float32, numpy=
array([-0.29641518, -0.43776062,  1.0762619 ,  0.15499532, -0.97992945,
        0.71167135,  1.2409165 , -0.58520615], dtype=float32)>], [<tf.Tensor: shape=(8, 10), dtype=float32, numpy=
array([[ 1.7901176 ,  1.7901176 ,  1.7901176 ,  1.7901176 ,  1.7901176 ,
         1.7901176 ,  1.7901176 ,  1.7901176 ,  1.7901176 ,  1.7901176 ],
       [ 0.03700554,  0.03700554,  0.03700554,  0.03700554,  0.03700554,
         0.03700554,  0.03700554,  0.03700554,  0.03700554,  0.03700554],
       [-0.05117702, -0.05117702, -0.05117702, -0.05117702, -0.05117702,
        -0.05117702, -0.05117702, -0.05117702, -0.05117702, -0.05117702],
       [-0.14827